### ISSUE TITLE
Encrypt the values stored in the local storage

### ISSUE THREAD

**Issue by jamil-stark** [Hussseinkizz/_useLocalStorage#1]
Some data stored in the browser is sensitive and not fit for all to view in plain text.
It would be very better if the values stored are only interpreted by the code.
When I use Localstorage, the text is encrypted and when I retrieve, it is decrypted.

**Comment by Hussseinkizz** [comment]
Noted, encryption of stored data is coming in next update!

**Comment by Hussseinkizz** [comment]
We have added this feature, so am closing for now!
